# CMake generated Testfile for 
# Source directory: /home/qhuang/templateV2/template
# Build directory: /home/qhuang/templateV2/template
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testBewaesserungOhneRegen "/home/qhuang/templateV2/template/ha2" "testBewaesserungOhneRegen")
set_tests_properties(testBewaesserungOhneRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testBewaesserung30Grad "/home/qhuang/templateV2/template/ha2" "testBewaesserung30Grad")
set_tests_properties(testBewaesserung30Grad PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testBewaesserungMitPreRegen "/home/qhuang/templateV2/template/ha2" "testBewaesserungMitPreRegen")
set_tests_properties(testBewaesserungMitPreRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testBewaesserungMitMidRegen "/home/qhuang/templateV2/template/ha2" "testBewaesserungMitMidRegen")
set_tests_properties(testBewaesserungMitMidRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testBewaesserungMitDauerRegen "/home/qhuang/templateV2/template/ha2" "testBewaesserungMitDauerRegen")
set_tests_properties(testBewaesserungMitDauerRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testBlattlaeuseKuerbisfeld "/home/qhuang/templateV2/template/ha2" "testBlattlaeuseKuerbisfeld")
set_tests_properties(testBlattlaeuseKuerbisfeld PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testBlattlaeuseSalatfeld "/home/qhuang/templateV2/template/ha2" "testBlattlaeuseSalatfeld")
set_tests_properties(testBlattlaeuseSalatfeld PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testSchneckenSalatfeld "/home/qhuang/templateV2/template/ha2" "testSchneckenSalatfeld")
set_tests_properties(testSchneckenSalatfeld PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testWarnlampeAusAn "/home/qhuang/templateV2/template/ha2" "testWarnlampeAusAn")
set_tests_properties(testWarnlampeAusAn PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testWarnlampeRegenLoop "/home/qhuang/templateV2/template/ha2" "testWarnlampeRegenLoop")
set_tests_properties(testWarnlampeRegenLoop PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testOverflowBauer "/home/qhuang/templateV2/template/ha2" "testOverflowBauer")
set_tests_properties(testOverflowBauer PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testDuengungOhneRegen "/home/qhuang/templateV2/template/ha2" "testDuengungOhneRegen")
set_tests_properties(testDuengungOhneRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testDuengungMitRegen "/home/qhuang/templateV2/template/ha2" "testDuengungMitRegen")
set_tests_properties(testDuengungMitRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testDuengungMitDauerRegen "/home/qhuang/templateV2/template/ha2" "testDuengungMitDauerRegen")
set_tests_properties(testDuengungMitDauerRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testDuengungNachRegen "/home/qhuang/templateV2/template/ha2" "testDuengungNachRegen")
set_tests_properties(testDuengungNachRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUeber30GradSonnig "/home/qhuang/templateV2/template/ha2" "testTemperaturUeber30GradSonnig")
set_tests_properties(testTemperaturUeber30GradSonnig PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUeber30GradRegen "/home/qhuang/templateV2/template/ha2" "testTemperaturUeber30GradRegen")
set_tests_properties(testTemperaturUeber30GradRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUeber30GradBewoelkt "/home/qhuang/templateV2/template/ha2" "testTemperaturUeber30GradBewoelkt")
set_tests_properties(testTemperaturUeber30GradBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUeber30GradStarkBewoelkt "/home/qhuang/templateV2/template/ha2" "testTemperaturUeber30GradStarkBewoelkt")
set_tests_properties(testTemperaturUeber30GradStarkBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUeber30GradDunkel "/home/qhuang/templateV2/template/ha2" "testTemperaturUeber30GradDunkel")
set_tests_properties(testTemperaturUeber30GradDunkel PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUnter30GradSonnig "/home/qhuang/templateV2/template/ha2" "testTemperaturUnter30GradSonnig")
set_tests_properties(testTemperaturUnter30GradSonnig PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUnter30GradRegen "/home/qhuang/templateV2/template/ha2" "testTemperaturUnter30GradRegen")
set_tests_properties(testTemperaturUnter30GradRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUnter30GradBewoelkt "/home/qhuang/templateV2/template/ha2" "testTemperaturUnter30GradBewoelkt")
set_tests_properties(testTemperaturUnter30GradBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUnter30GradStarkBewoelkt "/home/qhuang/templateV2/template/ha2" "testTemperaturUnter30GradStarkBewoelkt")
set_tests_properties(testTemperaturUnter30GradStarkBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testTemperaturUnter30GradDunkel "/home/qhuang/templateV2/template/ha2" "testTemperaturUnter30GradDunkel")
set_tests_properties(testTemperaturUnter30GradDunkel PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeOhneRegenSonnig "/home/qhuang/templateV2/template/ha2" "testLampeOhneRegenSonnig")
set_tests_properties(testLampeOhneRegenSonnig PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeOhneRegenBewoelkt "/home/qhuang/templateV2/template/ha2" "testLampeOhneRegenBewoelkt")
set_tests_properties(testLampeOhneRegenBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeOhneRegenStarkBewoelkt "/home/qhuang/templateV2/template/ha2" "testLampeOhneRegenStarkBewoelkt")
set_tests_properties(testLampeOhneRegenStarkBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeOhneRegenDunkel "/home/qhuang/templateV2/template/ha2" "testLampeOhneRegenDunkel")
set_tests_properties(testLampeOhneRegenDunkel PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeMitRegenSonnig "/home/qhuang/templateV2/template/ha2" "testLampeMitRegenSonnig")
set_tests_properties(testLampeMitRegenSonnig PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeMitRegenbewoelkt "/home/qhuang/templateV2/template/ha2" "testLampeMitRegenbewoelkt")
set_tests_properties(testLampeMitRegenbewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeMitRegenStarkBewoelkt "/home/qhuang/templateV2/template/ha2" "testLampeMitRegenStarkBewoelkt")
set_tests_properties(testLampeMitRegenStarkBewoelkt PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeMitRegenDunkel "/home/qhuang/templateV2/template/ha2" "testLampeMitRegenDunkel")
set_tests_properties(testLampeMitRegenDunkel PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
add_test(testLampeMitUndOhneRegen "/home/qhuang/templateV2/template/ha2" "testLampeMitUndOhneRegen")
set_tests_properties(testLampeMitUndOhneRegen PROPERTIES  _BACKTRACE_TRIPLES "/home/qhuang/templateV2/template/CMakeLists.txt;55;add_test;/home/qhuang/templateV2/template/CMakeLists.txt;0;")
